image: node:alpine

cache:
  paths:
    - node_modules/

build site:
  stage: build
  script:
    - npm install --progress=false
    - npm run build

before_script:
  - apk update
  - which ssh-agent || apk add openssh
  - which rsync || apk add rsync
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | ssh-add -

deploy_stage:
  stage: deploy
  only:
    - staging
  script:
    - npm run build
    - rsync -hrvz --delete --exclude=_ -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' . prod@siscoding.club:~/dev/projects/piano/

deploy_live:
  stage: deploy
  only:
    - master
  script:
    - npm run build
    - rsync -hrvz --delete --exclude=_ -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i id_rsa' . prod@siscoding.club:~/app/projects/piano/

