image: node:alpine

build site:
  stage: build
  script:
    - npm install --progress=false
    - npm run build

deploy_stage:
  stage: deploy
  environment: staging
  only:
    - staging
  script:
    - apk update
    - apk add rsync openssh
    - echo "${SSH_PRIVATE_KEY}" > id_rsa
    - chmod 700 id_rsa
    - rsync -hrvz --delete --exclude=_ -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i id_rsa' / prod@siscoding.club:~/prod/dev/projects/piano/

deploy_live:
  stage: deploy
  environment: production
  only:
    - master
  script:
    - apk update
    - apk add rsync openssh
    - echo "${SSH_PRIVATE_KEY}" > id_rsa
    - chmod 700 id_rsa
    - rsync -hrvz --delete --exclude=_ -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i id_rsa' / prod@siscoding.club:~/prod/app/projects/piano/

